### ISSUE TITLE
发现插件存在两个问题

### ISSUE THREAD

**Issue by Mr-xue** [chiic/vue-contextmenu#13]
1.document的mouseup事件好像有重复绑定的问题，每次mouseup后，再次执行都会重复绑定一次，建议作者可以看一下。

2.关于边界值判断
var distanceToBottm = document.body.clientHeight - menu.offsetTop - menuHeight
是不是改为以下更好一些，否则距离底部还有足够展示菜单的距离，菜单反而会跑到上面展示（左右同理）
var distanceToBottm = document.body.clientHeight - menu.offsetTop

**Comment by wuyungen1996** [comment]
遇到了越界问题，希望作者能修复下

**Comment by chiic** [comment]
@Mr-xue 确实是有问题，之前没有测试完全，会修复
