### ISSUE TITLE
ie 不兼容(Incompatible)  "preventDefault"   问题修复(Problem fixing)

### ISSUE THREAD

**Issue by wangliquanF** [chiic/vue-contextmenu#14]
//判断IE浏览器
document.all ? window.event.returnValue = false : event.preventDefault();

**Comment by chiic** [comment]
@wangliquanF 会采纳

**Comment by chiic** [comment]
@wangliquanF 这个兼容问题应该算插件以外的了，只是阻止事件冒泡，可以自行处理
