### ISSUE TITLE
关于Lincese

### ISSUE THREAD

**Issue by FUN-0810** [chiic/vue-contextmenu#19]
你好，我们在开发中正好利用了你的整个控件，对我们有非常大的帮助。
但是因为要利用你的控件，我们想要明确你的控件的使用License，请问能否把你该控件的使用License文件上传到GitHub项目上面。
给您添麻烦了。

**Comment by chiic** [comment]
MIT

**Comment by chiic** [comment]
@FUN-0810 OK, MIT
