### ISSUE TITLE
it has been always generating some mistakes

### ISSUE THREAD

**Issue by WayneBatman** [chiic/vue-contextmenu#3]
Hi, chllC,
     When I do as what you say on readme.Md,there is always some mistakes.
     One of them is here:
     [Vue warn]: Failed to mount component: template or render function not defined.
     Actullay i use the code of your second example.
    Do you know the reason?

**Comment by chIIC** [comment]
It's my fault,i'm too busy this time。There are some mistakes in the Readme.md document,I updated it now.thanks.
